spring:
  application:
    name: encryptionapp
  datasource:
    url: jdbc:postgresql://localhost:5432/encryption_database
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

encryption:
  secret-key: sC69g8gpvzruen7MVnuwtLEMoQXDviud